package:
  name: "pydistro_testing"
  version: "1.4.2"

source:
  path: ../src

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python

about:
  home: https://github.com/spatterson82/pydistro_testing
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Testing of open-source python publishing"

extra:
  recipe-maintainers:
    - spatterson82